# Generated by Django 2.1.2 on 2018-10-18 15:03

import base_file_server.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseFile',
            fields=[
                ('created', models.DateField(auto_created=True, blank=True, editable=False)),
                ('modified', models.DateField(auto_now=True)),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('id', models.UUIDField(default='8033d38fc55f4337a644985487fe38f0', primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TypeImg',
            fields=[
                ('basefile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_file_server.BaseFile')),
                ('file', models.FileField(upload_to=base_file_server.models.TypeImg.file_upload_dir)),
            ],
            bases=('base_file_server.basefile',),
        ),
    ]
