# Generated by Django 2.1.2 on 2018-10-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_file_server', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basefile',
            name='name',
        ),
        migrations.AlterField(
            model_name='basefile',
            name='created',
            field=models.DateField(auto_created=True, editable=False),
        ),
        migrations.AlterField(
            model_name='basefile',
            name='id',
            field=models.UUIDField(default='24e8057f3ff14f0e86ed7a4aa8611a0a', primary_key=True, serialize=False),
        ),
    ]
